{
 "title": "NYC Taxi Prediction Dashboard",
 "time": { "from": "2021-01-01T00:00:00.000Z", "to": "2021-01-31T00:00:00.000Z" },
 "panels": [
  {
   "title": "Number of Share Missing Value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  share_missing_values\nFROM\n  dummy_metrics\nORDER BY\n  timestamp"
    }
   ]
  },
  {
   "title": "Number of Drift Columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  num_drifted_columns\nFROM\n  dummy_metrics\nORDER BY\n  timestamp"
    }
   ]
  },
  {
   "title": "Prediction Drift ",
   "type": "timeseries",
   "description": "This time series chart shown the prediction drift of the NYC taxi data prediction ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  prediction_drift\nFROM\n  dummy_metrics\nORDER BY\n  timestamp"
    }
   ]
  }
 ]
}