source_stream_name = "stgs_ride_events"
output_stream_name = "stgs_ride_predictions"
model_bucket = "stgs-mlflow-models-code-owners"
lambda_function_local_path = "../lambda_function.py"
docker_image_local_path = "../Dockerfile"
ecr_repo_name = "stgs_stream_model_duration"
lambda_function_name = "stgs_prediction_lambda"